### ISSUE TITLE
Game crash on smeltery GUI

### ISSUE THREAD

**Issue by snacdaws** [SlimeKnights/TinkersConstruct#1538]
here is the crash report

http://pastebin.com/45UKTnSk

**Comment by snacdaws** [comment]
i reloaded forge 10.13.2.1291 and it works again

it seems to be an issue with forge 10.13.3.1370

**Comment by TherminatorX** [comment]
That would be correct.
Fixed in repository earlier this week.

**Comment by romancandle** [comment]
Also having this issue on 10.13.3.1360

**Comment by bonii-xx** [comment]
<1355 is what you want

**Comment by romancandle** [comment]
Still crashing after switching to 1355 http://pastebin.com/FwvvWcnC

**Comment by romancandle** [comment]
Looks like I'm SOL until forge gets updated, I can't use any version below 1355 (which also crashes my client) because some of the mods I'm using are dependent on the newer versions...

**Comment by bonii-xx** [comment]
Use the alpha version

**Comment by snacdaws** [comment]
Alpha version..... Now I'm confused

**Comment by romancandle** [comment]
if you mean 1370, I've already tried that. And I still crash. I'm just spawning the items I have the materials for and deleting the materials as I go. i.e. spawn 1 deep iron pickaxe head and delete 1 alumin, 1 copper and 1 deep iron, I've already lost 5 buckets of lava to this little bug so I'll call that fair.

**Comment by snacdaws** [comment]
Hey romancandle I'm using 1291 fine but I know what you mean

My whole minecraft setup got messed up yesterday for no reason

Just use 1291 and you should not have the gui issue

**Comment by romancandle** [comment]
Ok, but I dont see it on the downloads page, could you link it please?

**Comment by snacdaws** [comment]
http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.7.10.html

It's under recommended version instead of latest version

**Comment by romancandle** [comment]
Thanks!

**Comment by snacdaws** [comment]
No problem literally

**Comment by snacdaws** [comment]
I've had problems with anything above 1307 myself so I think I'll be good on 1291

**Comment by Cooolaid** [comment]
TherminatorX - If this has been fixed as you mention and you say its in the repository ("what ever that means") 
Why is it that I still cant find it on Curse so i can download it.

Also, I see many people here mentioning to downgrade to 1291.
There is a problem with that. The problem is, Tinkers is not the only mod in peoples mod packs.
Many mods right now require Forge 1355+
And most people update to newest version of their mods to keep up to date.
So if people downgrade their foge, it will break all other mods they have installed in the mod packs and break their worlds, and have even bigger problems.
I really wish people stop saying downgrade Tinkers. seriously.
If there is a fix, please make it available so the error / crash reports would stop coming in and we can move on.

thx,.

**Comment by snacdaws** [comment]
If we weren't forced to downgrade to make it playable we simply wouldn't need to but the fact is they don't seem to want to give us the fix @cooolaid

**Comment by bonii-xx** [comment]
@Cooolaid there is a public version for 1355, and either all your mods require 1355+ or none. If people don't know what they're doing, they probably shouldn't touch that stuff anyway.

**Comment by Cooolaid** [comment]
you mean --> Latest v1.7.10 File: TConstruct-1.7.10-1.8.3b.jar - That one is currently giving fluid problems.

**Comment by bonii-xx** [comment]
That's because it's an alpha: http://minecraft.curseforge.com/mc-mods/74072-tinkers-construct/files/2234077
As I said, if people don't know what they're doing they should stick with 1291 until everything updated.

**Comment by Cooolaid** [comment]
ok thx.
it seems there are 2 different pages for tinkers.
http://www.curse.com/mc-mods/minecraft/tinkers-construct
and
http://minecraft.curseforge.com/mc-mods/74072-tinkers-construct

Not Enough mods webpage throws me to the first link, and not the second.
something you might want to look into.
thanks for the proper link :)

**Comment by Cooolaid** [comment]
I think I found a little glitch, using (TConstruct-1.7.10-1.8.4RC1.jar)
look at these pictures & pay close attention to NEI when you switch pictures. 
This is what happens when I hover my mouse pointer over 
the liquid in the smelter GUI.

http://i.imgur.com/IEJ2X2p.png  <-- without hovering
x
http://i.imgur.com/xwrsIHq.png  <-- with hovering
.
.

**Comment by snacdaws** [comment]
@cooolaid that happens in 1.8.3b as well

Looks like they haven't fixed it yet

**Comment by snacdaws** [comment]
It may be nei messing up as well or forge even

Who knows

**Comment by Cooolaid** [comment]
Boni,
Another little glitch I found using (TConstruct-1.7.10-1.8.4RC1.jar)
When creating (Aluminium Brass Template) with a tool part.
The smelter seems to destroy the tool part. - Dont know if this was intended.
Just giving the heads up on it.
